### ISSUE TITLE
Use Base58 instead of base85

### ISSUE THREAD

**Issue by idenatoday** [Idena-Today/DnaUrl#3]
@menxit suggests to use base58 encoding instead of current base85.

`I would prefer base58 instead of base85:

- Base85:  dna://0xf2b4f700d2975abd39000587f9788f66afedf691/10/NM&qnZy;%8Wo}^/;er(onnZKbDzEZk

- Base58: dna://0xf2b4f700d2975abd39000587f9788f66afedf691/10/3ESZ4Y/2G5JnrxQeoHSDbkSiCMDGtBjsFKo

Base85 consumes less space, but it includes special characters that a lot of social network escape, preventing hyperlink (e.g. try to paste a base85 link in telegram).`

This makes sense.

A/ Use base58 as default, drop base85 and update now while there is no dependency yet.
B/ Evolve to v2, keep v1 as historical reference
C/ Give the choice

We see little use in C, since it defeats the common protocol goal.
B/ could mean overhead to keep just history

So we would go with A/ and change the specs and matching impl before they are widely used.

Feedback?

**Comment by leahcornelius** [comment]
It also prevents double click copying, i would suggest you use a alphanumerical breaker to allow me to double click to select it. eg use / encoded in bse58 as a breaker rather than the current set up

**Comment by idenatoday** [comment]
Thanks for the feedback leocornelius.
However, separator can't be a char from the encoder charset ;)

As for double click select, this is a url based string, following urls rules.
"protocol://" then segments.
js client side will allow to "click to copy" the full url, whereas double click a segment allows to select that segment alone, like the recipient address. So it's actually a feature.

**Comment by Endogen** [comment]
i'm for A/
makes sense. let's do it right from the beginning

**Comment by idenatoday** [comment]
Implemented and tested.
